Repository doprz/dipc, pull requests merged in 2023-04, with the labels that each got.

#11 Fixed #10
  src/cli.rs
  src/main.rs
  src/palettes.rs
Labels: bug

#14 add palette: Dracula
  src/cli.rs
  src/palettes.rs
  src/palettes/dracula.json
Labels: new theme

#15 feat: progress bar for processing image(s)
  Cargo.toml
  src/main.rs
Labels: enhancement
